services:

  # ── Prometheus ──────────────────────────────────────────────
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - devops-net

  # ── Grafana ─────────────────────────────────────────────────
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - devops-net

  # ── Node Exporter ───────────────────────────────────────────
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - devops-net

  # ── MongoDB ─────────────────────────────────────────────────
  mongo:
    image: mongo:7
    container_name: devops-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - devops-net

  # ── Backend ─────────────────────────────────────────────────
  backend:
    build: ./backend
    container_name: devops-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      MONGO_URI: mongodb://mongo:27017/devops_dashboard
    depends_on:
      - mongo
    networks:
      - devops-net

  # ── Frontend ────────────────────────────────────────────────
  frontend:
    build: ./frontend
    container_name: devops-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - devops-net

# ── Volumes ───────────────────────────────────────────────────
volumes:
  mongo_data:
  grafana_data:

# ── Networks ──────────────────────────────────────────────────
networks:
  devops-net:
    driver: bridge